### ISSUE TITLE
cross database compatibility

### ISSUE THREAD

**Issue by ak4t0sh** [edloomio/moodle-report_cohort#10]
Some queries should be replaced using are not cross-db compatible due to 
`DATE_FORMAT()` and `FROM_UNIXTIME()` usage to compute completion_date. These functions does not exist on PostgreSQL.
You should use [userdate()](https://github.com/moodle/moodle/blob/a62e2759846a992f4a28ca82a9bd13dabbaffc70/lib/moodlelib.php#L2260) to format your timestamp.

Moreover "completion" value (YES/NO) should be passed to `get_string()` function to allow internationalisation.

**Comment by rajuptl21** [comment]
I have fixed highlighted issue.
