### ISSUE TITLE
release number

### ISSUE THREAD

**Issue by ak4t0sh** [edloomio/moodle-report_cohort#3]
Instead of using a date as release number I think you should implements Semantic versioning (https://semver.org/)
Example : 
1.0.0 => Major version or version which break backward compatibility
1.1.0 => Add features
1.1.1 => Bug fixing or small improvements

please note - this is a personal advice and not the Moodle release policy so this is not a blocker for approval in the plugins db.

**Comment by rajuptl21** [comment]
I have fixed highlighted issue.
